name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html  # Install pytest-html for generating the report

      - name: Run tests and generate HTML report
        run: |
          pytest --html=results.html  # Generate the HTML report

      - name: List files in current directory
        run: ls -R  # This will help you verify if the results.html file exists

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pytest-html-report
          path: results.html  # Upload the HTML report
